name: fetchdata

on:
  workflow_dispatch:
  schedule:
    - cron: '5/15 * * * *'
    
jobs:
  fetchdata:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.WORKFLOW_GIT_ACCESS_TOKEN }}

      - name: fetchdata
        run: .github/workflows/fetch.sh

      - name: push2repo
        run: |
          git config --global user.name "fetchdata.yml"
          git config --global user.email "fetchdata.yml@example.com"
          git add data/raw
          git commit -m "$GITHUB_WORKFLOW run $GITHUB_RUN_NUMBER"
          git push
