name: fetchdata

concurrency: 
  group: auto-master-commit
  cancel-in-progress: false

on:
  workflow_dispatch:
  schedule:
    - cron: '*/12 * * * *'
    
jobs:
  fetchdata:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - uses: actions/checkout@v5
        with:
          token: ${{ secrets.WORKFLOW_GIT_ACCESS_TOKEN }}

      - name: fetchdata
        run: .github/workflows/fetch.sh

      - name: push2repo
        run: |
          git config --global user.name "fetchdata.yml"
          git config --global user.email "fetchdata.yml@example.com"
          git add data
          git commit -m "$GITHUB_WORKFLOW run $GITHUB_RUN_NUMBER"
          git pull --rebase
          git push
